FROM php:8.1-apache

RUN apt-get update && apt-get install -y --no-install-recommends \
    libzip-dev libicu-dev libonig-dev \
    && docker-php-ext-configure intl \
    && docker-php-ext-install -j"$(nproc)" pdo_mysql mysqli zip intl mbstring opcache \
    && a2enmod rewrite \
    && rm -rf /var/lib/apt/lists/*
